API/Controllers/MediaItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MediaNest.Domain.Model;
using MediaNest.Application.UseCases.MediaManagment;

namespace API.Controllers
{
    public class MediaItemsController : Controller
    {
        // We implement the interface for servies (normally) because services adjusts the data given back by the Irepository files and adds extra logic (normally)
        // and so we depend on that implementation Controller <- Services <- Repository <- DB
        private readonly MediaItemService _mediaItemService;
        private static readonly string[] items = new[] { "SciFi", "Adventure", "Romance" };

        public MediaItemsController(MediaItemService mediaItemService)
        {
            _mediaItemService = mediaItemService;
        }

        // GET: MediaItems
        public async Task<IActionResult> Index()
        {
            return View(await _mediaItemService.GetMediaItemsAsync());
        }

        // GET: MediaItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mediaItem = await _mediaItemService.GetMediaItemById((int)id);
            if (mediaItem == null)
            {
                return NotFound();
            }

            return View(mediaItem);
        }

        // GET: MediaItems/Create
        public IActionResult Create()
        {
            ViewData["Genres"] = new MultiSelectList(items);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ISBN,Title,Description,Type,Year,Language,Genres,Rating")] MediaItem mediaItem)
        {
            if (ModelState.IsValid)
            {

                await _mediaItemService.AddMediaItem(mediaItem);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Genres = new MultiSelectList(items);

            return View(mediaItem);
        }

        // GET: MediaItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mediaItem = await _mediaItemService.GetMediaItemById((int)id);
            if (mediaItem == null)
            {
                return NotFound();
            }
            ViewBag.Genres = new MultiSelectList(items);

            return View(mediaItem);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ISBN,Title,Description,Type,Year,Language,Genres,Rating")] MediaItem mediaItem)
        {
            if (id != mediaItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _mediaItemService.UpdateMediaItem(mediaItem);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MediaItemExists(mediaItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mediaItem);
        }

        // GET: MediaItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mediaItem = await _mediaItemService.GetMediaItemById((int)id);
            if (mediaItem == null)
            {
                return NotFound();
            }

            return View(mediaItem);
        }

        // POST: MediaItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mediaItem = await _mediaItemService.GetMediaItemById(id);
            if (mediaItem != null)
            {
                await _mediaItemService.DeleteMediaItem(mediaItem);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool MediaItemExists(int id)
        {
            return _mediaItemService.Exists(id);
        }
    }
}

API/Controllers/MyCollectionController.cs
using API.ViewModels;
using MediaNest.Application.UseCases.UserCollectionManagment;
using MediaNest.Domain.Model;
using MediaNest.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace API.Controllers
{
    [Authorize]
    public class MyCollectionController : Controller
    {
        // DI on Interface UserCollectionService
        private readonly IUserCollectionService _userCollectionService;
        private UserManager<ApplicationUser> _userManager;

        public MyCollectionController(IUserCollectionService collectionService, UserManager<ApplicationUser> userManager)
        
        {
            _userCollectionService = collectionService;
            _userManager = userManager;

            }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            
            var id = user.Id;
            if (id is not null)
            {
                if (ModelState.IsValid)
                {
                    var viewModel = new MyCollectionViewModel
                    {
                        SearchRequest = new MediaItemSearchRequest
                        {
                            SearchText = string.Empty // Initialize required property  
                        },
                        Items = await _userCollectionService.GetAllUserMediaItems(id)
                    };
                    
                    return View(viewModel);
                }
                
            }
            return View();
        }

        [HttpPost]
        public async Task AddToCollection([FromBody] int mediaItemId) // pass in user id
        {
            if (ModelState.IsValid)
            {
                // get user first
                var user = await _userManager.GetUserAsync(User);
                var id = user.Id;
                if (id is not null)
                {
                    await _userCollectionService.AddToUserCollection(mediaItemId, id);
                }
                Console.Write(mediaItemId);
                Console.WriteLine(1);
            }
            
        }
    }
}

API/Controllers/SearchController.cs
using API.ViewModels;
using MediaNest.Application.UseCases.MediaManagment;
using MediaNest.Domain.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace API.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        
        private readonly MediaItemService _mediaItemService;


        public SearchController(MediaItemService mediaItems)
        {
            _mediaItemService = mediaItems;
        }
        public IActionResult Index()
        {
            var viewModel = new SearchPageViewModel
            {
                SearchRequest = new MediaItemSearchRequest
                {
                    SearchText = string.Empty // Initialize required property  
                },
                SearchResult = new List<MediaItem>()
            };
            return View(viewModel);
        }

        [HttpPost]
        // From body is from the js post 
        public async Task<IActionResult> SearchMediaItem([FromBody] MediaItemSearchRequest request)
        {
            if (request == null || string.IsNullOrEmpty(request.SearchText))
            {
                return BadRequest("Invalid search request.");
            }

            var results = await _mediaItemService.SearchMediaItems(request);
            return PartialView("_SearchResult", results);
        }

        // Show details + the option for user to add to list 
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return BadRequest("No Id Found");
            }
            var mediaItem = await _mediaItemService.GetMediaItemById((int)Id);
            return View(mediaItem);
        }
    }
}

API/Views/Shared/_Layout.cshtml
@using MediaNest.Infrastructure.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediaNest </title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/API.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary mb-3 p-3 text-white">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MediaNest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1 ">
                        
                        @if (User.IsInRole("Member"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="MyCollection" asp-action="Index">My Collection</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white">Discussion</a>
                            </li>
                        }else if(User.IsInRole("Admin"))
                        {
                        <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="MediaItems" asp-action="Index">Media Items</a>
                        </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MediaNest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>